/**
 * Demo grocery delivery ops rows until Backend exposes live orders + assignments.
 * `placedAtSort` is used for time-column sorting; `minutesInState` for urgency styling if needed later.
 */

export const groceryOpsDemoOrders = [
  {
    id: 'G-10428',
    placedAtSort: Date.now() - 18 * 60 * 1000,
    placedAtLabel: 'Today, 11:42',
    customerName: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    itemCount: 2,
    itemSummary: 'Basmati 5kg, Toor dal 1kg',
    area: 'Village A',
    addressShort: 'Ward 3, near bus stand',
    status: 'pending',
    agentName: null,
    minutesInState: 18,
  },
  {
    id: 'G-10427',
    placedAtSort: Date.now() - 6 * 60 * 1000,
    placedAtLabel: 'Today, 11:54',
    customerName: 'Amit Patil',
    phone: '+91 91234 55678',
    itemCount: 5,
    itemSummary: 'Milk, bread, eggs, oil, sugar',
    area: 'Village B',
    addressShort: 'Behind gram panchayat',
    status: 'confirmed',
    agentName: null,
    minutesInState: 6,
  },
  {
    id: 'G-10426',
    placedAtSort: Date.now() - 45 * 60 * 1000,
    placedAtLabel: 'Today, 11:15',
    customerName: 'Sunita Devi',
    phone: '+91 99887 77665',
    itemCount: 1,
    itemSummary: 'Atta 10kg',
    area: 'Village A',
    addressShort: 'Lane 2, blue gate',
    status: 'packed',
    agentName: 'Rahul M.',
    minutesInState: 45,
  },
  {
    id: 'G-10425',
    placedAtSort: Date.now() - 70 * 60 * 1000,
    placedAtLabel: 'Today, 10:50',
    customerName: 'Vikram Singh',
    phone: '+91 98123 44556',
    itemCount: 8,
    itemSummary: 'Weekly basket (mixed)',
    area: 'Village C',
    addressShort: 'Main road, opposite school',
    status: 'out_for_delivery',
    agentName: 'Rahul M.',
    minutesInState: 70,
  },
  {
    id: 'G-10424',
    placedAtSort: Date.now() - 14 * 60 * 1000,
    placedAtLabel: 'Today, 11:46',
    customerName: 'Priya Sharma',
    phone: '+91 97654 33221',
    itemCount: 3,
    itemSummary: 'Paneer, curd, butter',
    area: 'Village B',
    addressShort: 'Near dairy cooperative',
    status: 'pending',
    agentName: null,
    minutesInState: 14,
  },
  {
    id: 'G-10423',
    placedAtSort: Date.now() - 3 * 60 * 1000,
    placedAtLabel: 'Today, 11:57',
    customerName: 'Anil Kulkarni',
    phone: '+91 93456 77889',
    itemCount: 4,
    itemSummary: 'Snacks, juice, biscuits',
    area: 'Village A',
    addressShort: 'Plot 12, Shiv nagar',
    status: 'confirmed',
    agentName: 'Suresh P.',
    minutesInState: 3,
  },
  {
    id: 'G-10422',
    placedAtSort: Date.now() - 120 * 60 * 1000,
    placedAtLabel: 'Today, 10:00',
    customerName: 'Meena Joshi',
    phone: '+91 94567 88990',
    itemCount: 6,
    itemSummary: 'Vegetables + staples',
    area: 'Village C',
    addressShort: 'Old market lane',
    status: 'packed',
    agentName: null,
    minutesInState: 120,
  },
];
